spring.application.name=lab1
# === DATABASE CONFIGURATION ===
# URL ??? ??????????? ? ????? ??
spring.datasource.url=jdbc:postgresql://localhost:5432/tournament_db

# ??? ???????????? (?????? postgres)
spring.datasource.username=postgres

# ?????? ?? ?????????? ????????? DB_PASSWORD
spring.datasource.password=${DB_PASSWORD}

# === JPA/HIBERNATE CONFIGURATION ===
# ????????? Hibernate ????????????? ????????? ????? ?? (?????? ??? ??????????)
spring.jpa.hibernate.ddl-auto=update

# ?????????? SQL-??????? ? ??????? (??????? ??? ???????)
spring.jpa.show-sql=true

# ??????????? SQL-??????? ??? ?????? ??????????
spring.jpa.properties.hibernate.format_sql=true